apiVersion: v1
kind: Service
metadata:
  name: pansecurityadapter 
  namespace: istio-system
  labels:
    app: pansecurityadapter 
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 9693 
    targetPort: 9693 
  selector:
    app: pansecurityadapter 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pansecurityadapter 
  namespace: istio-system
  labels:
    app: pansecurityadapter 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pansecurityadapter 
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: pansecurityadapter 
        image: vinayvenkat/pan-servicemesh-security:panorama
        imagePullPolicy: Always
        ports:
        - containerPort: 9693 
        volumeMounts:
        - name: transient-storage
          mountPath: /volume
        env:
        - name: SECURITY_POLICY_API_ENDPOINT
          value: "35.202.184.1" 
        - name: PANORAMA_USERNAME
          value: YWRtaW4=
        - name: PANORAMA_PASSWORD
          value: dmluYXkxMjM=
      volumes:
      - name: transient-storage
        emptyDir: {}
